### ISSUE TITLE
not start, can you help me ?

### ISSUE THREAD

**Issue by osinter456** [pielco11/telescan#5]
python3 telescan.py api_creds.ini
Traceback (most recent call last):
  File "telescan.py", line 9, in <module>
    app = Client(
TypeError: __init__() got an unexpected keyword argument 'config_file'

**api_creds.ini**

[pyrogram]
api_id = 18XXXX76
api_hash = e11cXXXXXXXXXXXXXdcb

**Comment by osinter456** [comment]
up

**Comment by rangersmyth74** [comment]
Wow, they never got back to you since May? 

Just getting the same error myself. 

└─$ python telescan.py api_creds.ini
Traceback (most recent call last):
  File "/home/kali/apps/telescan/telescan.py", line 9, in <module>
    app = Client(
TypeError: Client.__init__() got an unexpected keyword argument 'config_file'

**Comment by pielco11** [comment]
Closing this, conversation moved to #6
